server:
  port: 10088
spring:
  application:
    name: nas-video #指定服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel_system?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 200451